### ISSUE TITLE
Can provide a maven jmh report?

### ISSUE THREAD

**Issue by liushoukai** [jzillmann/gradle-jmh-report#8]
Can provide a maven jmh report?

**Comment by jzillmann** [comment]
I saw that coming ;)
But honestly i don't want the burden of managing another project for the jmh tooling. However, it should be pretty straightforward to implement:
- bundle files from https://github.com/jzillmann/jmh-visualizer into the jar
- generate a js file containing the jmh result json
- put everything into the right project location

If you somebody wants to work on this i'm happy to provide more guidance and we could also discuss extracting common code to a separate project which would make upgrades even easier...
